services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adote-vica-web
    ports:
      - "8080:80"
    volumes:
      - ./duplicator:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: adote-vica-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: